
name: Build HRTV APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: hrtv-apk
          path: app/build/outputs/apk/debug/app-debug.apk
